MANAGER:
    NR_OF_PARALLEL_WORKERS: -1  # -1 means half of the available processors will be used
    SITE_VERTICES_FILE:
        PATH: "../random_idf_generator/data/Random_SiteVertices.csv"
        SEPARATOR: ","
    BLDG_FID_FILE:
        PATH: "../random_idf_generator/data/Random_BuildingInformation.csv"
        SEPARATOR: ","
    BLDG_AGE_FILE:
        PATH: "../random_idf_generator/data/Random_BuildingInformation.csv"
        SEPARATOR: ","
    BLDG_TYPE_PER_BLDG_FILE:
        PATH: "../random_idf_generator/data/Random_BuildingInformation.csv"
        SEPARATOR: ","
    DO_CALC_OP_EMISSIONS_AND_COSTS: False
    SINGLE_SITE:
        ACTIVE: True
        WEATHER_FILE: "../random_idf_generator/data/Weather.epw"


# You can add here custom configuration for the cesar-p packages. This will overwrite package default config.
# For configuration options see the configuration overview cesar-p-config_overview.yaml in the root of cesar-p-core
# or see Configuration overview in the Usage section of the documentation
